pipeline {
    agent any
    environment {
        PATH = "/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:$PATH"
    }
    stages {
        stage('Build') {
            steps {
                echo "Build Docker Image"
                sh "docker build -t mypythonflaskapp ."
            }
        }
        stage('Run') {
            steps {
                echo "Run application in Docker Container on port 5002"
                sh "docker rm -f mycontainer || true"
                sh "docker run -d -p 5002:5002 --name mycontainer mypythonflaskapp"
            }
        }
    }
    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}