
pipeline {
    agent any

    environment {
        PATH = "/Applications/Docker.app/Contents/Resources/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
        KUBECONFIG = '/Users/nuhakhan/.kube/config'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                dir('week9') {
                    echo "Build Docker Image"
                    sh "docker build -t kubdemoapp:v1 ."
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASSWORD'
                )]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                dir('week9') {
                    echo "Push Docker Image to Docker Hub"
                    sh "docker tag kubdemoapp:v1 nuhakhan1305/kubedemoapp:v1"
                    sh "docker push nuhakhan1305/kubedemoapp:v1"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('week9') {
                    sh 'kubectl apply -f deployment.yaml --validate=false'
                    sh 'kubectl apply -f service.yaml'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}
